improving setup fail checking

diff --git a/bin/setup b/bin/setup
--- a/bin/setup
+++ b/bin/setup
@@ -1,12 +1,4 @@
 #!/bin/bash
-IMG="https://cdimage.ubuntu.com/releases/20.04.1/release/ubuntu-20.04.1-preinstalled-server-arm64+raspi.img.xz?_ga=2.62032367.234707340.1608229182-200893871.1586502931"
-NAME=ubuntu-20.04-cm3
-OKG='\033[92m'
-# WARNING='\033[93m'
-# FAIL='\033[91m'
-OKB='\033[94m'
-# UNDERLINE='\033[4m'
-NC='\033[0m'
 
 build(){
   cd "$BUILD" || exit
@@ -14,28 +6,32 @@ build(){
   cd - || exit
 }
 
-echo "Installing dependancies ..."
+build_usbboot(){
+  git submodule update --init --recursive
+  echo "Syncing with upstream usbboot"
+  git submodule update --remote
+  cd usbboot
+  make
+}
+
+printf "%b" "${OKB}Installing homebrew dependancies ...${}"
 xargs brew install < dependencies.txt
-echo -e "${OKG} ✓ ${NC} complete"
+printf "%b" "${OKG} ✓ ${NC} complete\n"
 
 printf "${OKB}Preparing usbboot submodule ...${NC}"
-git submodule update --init --recursive
-echo "Syncing with upstream usbboot"
-git submodule update --remote
-cd usbboot || exit
-make
-printf "${OKG} ✓ ${NC} complete"
+build_usbboot && printf "%b" "${OKG} ✓ ${NC} complete\n" ||
+  printf "%b" "${FAIL} ✗ ${NC} usbboot build failed.\n" && exit 1;
 
-echo "Preparing build ... "
+echo "Preparing build ..."
 mkdir build
-build_path="$(cd build || exit; pwd -P)"
+build_path="$(cd build || exit 1; pwd -P)"
 export BUILD="$build_path"
 printf "${OKG} ✓ ${NC} complete"
 
-printf "${OKB}Fetching latest Ubuntu 20.04 release for CM3+ ...${NC}\n"
+printf "%b" "${OKB}Fetching latest Ubuntu 20.04 release for CM3+${NC}\n"
 curl -L  "${IMG}" --output build/"$NAME".xz
-printf "${OKG} ✓ ${NC} complete"
+printf "%b" "${OKG} ✓ ${NC} complete\n"
 
 echo "Extracting Ubuntu img ..."
 build
-printf "${OKG} ✓ ${NC} complete"
+printf "%b" "${OKG} ✓ ${NC} complete\n"
