fixing conditional bug

diff --git a/scripts/flash-emmc b/scripts/flash-emmc
--- a/scripts/flash-emmc
+++ b/scripts/flash-emmc
@@ -33,13 +33,21 @@ echo " 3. This local machine is connected to the slave micro usb flash port"
 read -rp "Press any key to continue ..."
 
 printf "%b" "${OKB}Starting eMMC Flashing Service ${NC}\n"
-usbboot && printf "%b" "${OKG} ✓ ${NC} complete\n" || 
-	( printf "%b" "${FAIL} ✗ ${NC} usbboot sequence failed.\n" && exit 1 )
+if usbboot ; then
+    printf "%b" "${OKG} ✓ ${NC} complete\n"
+else
+    printf "%b" "${FAIL} ✗ ${NC} usbboot sequence failed.\n"
+    exit 1
+fi
 
 sleep 2
 
-flash && printf "%b" "${OKG} ✓ ${NC} complete\n" || 
-	( printf "%b" "${FAIL} ✗ ${NC} emmc flash failed.\n" && exit 1 )
+if flash ; then
+    printf "%b" "${OKG} ✓ ${NC} complete\n"
+else
+    printf "%b" "${FAIL} ✗ ${NC} emmc flash failed.\n"
+    exit 1
+fi
 
 printf "%b" "${OKG} ✓ ${NC} Completed eMMC Flashing Service\n"
 echo "Please remove the compute module from the SO-DIMM slot, disconnect the usb flash cable and reinsert it to start boot process"
diff --git a/scripts/setup b/scripts/setup
--- a/scripts/setup
+++ b/scripts/setup
@@ -18,8 +18,13 @@ printf "%b" "${OKB}Installing homebrew dependancies ...${NC}\n"
 printf "%b" "${OKG} ✓ ${NC} complete\n"
 
 printf "%b" "${OKB}Preparing usbboot submodule ...${NC}\n"
-build_usbboot && printf "%b" "${OKG} ✓ ${NC} complete\n" || 
-  (printf "%b" "${FAIL} ✗ ${NC} usbboot build failed.\n" && exit 1)
+
+if build_usbboot ; then
+    printf "%b" "${OKG} ✓ ${NC} complete\n"
+else
+    printf "%b" "${FAIL} ✗ ${NC} usbboot build failed.\n"
+    exit 1
+fi
 
 mkdir build
 printf "%b" "${OKB}Fetching latest Ubuntu 20.04 release for CM3+${NC}\n"
@@ -27,5 +32,9 @@ curl -L "$IMG" --output build/"$NAME"
 printf "%b" "${OKG} ✓ ${NC} complete\n"
 
 echo "Extracting Ubuntu img ..."
-build && printf "%b" "${OKG} ✓ ${NC} complete\n" || 
-  (printf "%b" "${FAIL} ✗ ${NC} Failed to extract ubuntu image.\n" && exit 1)
+if build ; then
+    printf "%b" "${OKG} ✓ ${NC} complete\n"
+else
+    printf "%b" "${FAIL} ✗ ${NC} Failed to extract ubuntu image.\n"
+    exit 1
+fi
